import React from "react";
import type { Metadata } from "next";
import { FinancialProvider } from "@/context/FinancialContext";
import MainHeader from "@/components/Header/MainHeader";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <FinancialProvider>
          <MainHeader />
          {children}
        </FinancialProvider>
      </body>
    </html>
  );
}
