import React from "react";
import type { Metadata } from "next";
import { FinancialProvider } from "@/context/FinancialContext";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <FinancialProvider>
          {children}
        </FinancialProvider>
      </body>
    </html>
  );
}
